config/routes.rb
Rails.application.routes.draw do
  
  resources :tags

  get 'groups/search' => 'groups#search'
  get 'groups/places' => 'groups#places'
resources :groups do

  resources :events do 
resources:comments
end
end
get 'events/find' => 'events#find'
post 'groups/action'
post 'events/action'

resources :users
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :sessions
root :to => "groups#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
has_many :events ,dependent: :destroy
has_many :group_memebers , dependent: :destroy
has_many :tag_groups , dependent: :destroy

validates :topicname, presence: true
validates :description, presence: true

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  geocoded_by :location  # can also be an IP address
after_validation :geocode          # auto-fetch coordinates

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
def new
  @group = Group.new
@tags=Tag.all
@selected=params[:data]
@id=params[:id]
respond_to do |format|
      format.html
      format.json {render json: [@selected ,@id]}

    end
end


def search
  
  if (params[:location] == "")
      if(current_user)

    @location=current_user.city+","+current_user.country

  end
else
  @location =params[:location]
   end 
  @distance =params[:distance]
  if(params[:tag] != "")
  @tag = Tag.where("name = ?",params[:tag])
  
  @groups_tags=TagGroup.where("tag_id = ?",@tag[0].id)
  @group_ids =[];
  @groups_tags.each do |group_tag|
    @group_ids.push(group_tag.group_id)
  end
  @groups= Group.where("id IN (?)",@group_ids).near(@location, @distance)
  # @groups=@groups
else
  @groups=Group.near(@location, @distance)
end
  render 'index'


end  

def index
    @groups = Group.last(5).reverse
  end


def create
  @group = Group.new(group_params)


    x=params.require(:tag).permit(:id)
tag_id=x['id']
all_tag=tag_id.split(',')


x=all_tag.length-1
 if  @group.save  


  @coors=Geocoder.coordinates(@group.location)
  @group.latitude=@coors[0]
  @group.longitude=@coors[1]


	group_id=Group.last.id 
(0..x).each do |i|	 
   @tag_group = TagGroup.new(:group_id=> group_id,:tag_id=> all_tag[i])

@tag_group.save
 end
  redirect_to @group
else
render 'new'
  
end
end




def show
    @group = Group.find(params[:id])
    if( current_user )
@id=current_user.id
@group_id=params[:id]
@groupmemebe = GroupMemeber.where({:group_id=>@group_id,:user_id=>@id})
@groupcount = GroupMemeber.where({:group_id=>@group_id})  
@groupadmin = Group.where({:id=>@group_id,:user_id=>@id}) 

@count=@groupcount.count
end

end




def edit

@group=Group.find(params[:id])
end

def update

@group=Group.find(params[:id])
if @group.update(group_params) 
redirect_to @group
else 
render 'edit'
end
end

def destroy
@group=Group.find(params[:id])
group_id=params[:id]



if @group.destroy 
redirect_to groups_path

end
end

def action

	@groupmemeber = GroupMemeber.new(groupmemeber_params)
@groupmemeber.save
	id=GroupMemeber.last.group_id 

redirect_to group_path(:id=>id)
end



private
  def group_params


    params.require(:group).permit(:topicname, :description, :avatar, :location, :latitude, :longitude, :user_id)


  end
 def tag_params
    params.require(:tag).permit(:name)
  end
def grouptag_params
    params.require(:grouptag).permit(:group_id,:tag_id)
  end
def groupmemeber_params

 params.permit(:group_id,:user_id)
  end


end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <h1 class="page-header">Editing an Existing Group</h1>
<%= form_for :group ,url:group_path(@group),method: :put do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :topicname,class:"form-control",placeholder:"edit title here ....." %>
  </div>
  <% if @group.errors[:topicname].present? %>
          title can`t be blank
  <% end %>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description ,class:"form-control" %>
  </div>
  <% if @group.errors[:description].present? %>
          description can`t be blank
  <% end %>

  <div class="form-group">
  <%= f.file_field :avatar %>
</div>
 
 <div class="form-group">
    <%= f.submit class:"btn btn-warning"%>
  </div>

 
<% end %>
</div>

app/views/groups/index.html.erb
<%= image_tag("meetup.jpg", class:'center-block') %>
<div class="container">
<div style="background-color:#696969;height:50px">
    <%= form_tag({controller: "groups", action: "search"}, method: "get", class: "form-inline") do %>
                <%= text_field_tag(:tag,'', placeholder: 'Search for interests ...',
                                   class: 'form-control input-lg') %>
                <%= select_tag(:distance, options_for_select(['2 km','5 km','10 km','25 km','50 km','100 km','Any
                distance']), class: 'form-control input-lg') %>
                
                <%= select_tag :location, 
    options_for_select(['Alexandria,Egypt','Cairo,Egypt']),
    class: 'form-control input-lg' %>
                <%= submit_tag("Groups", class: 'btn-lg btn-primary pull-right') %>
             <%= link_to 'Calendar',events_find_path, class:"btn-lg btn-default pull-right" %>
            <% end %>

	
	
</div>	

 

 <div class="row">
  <% @groups.each do |group| %>
  <div class="col-sm-4" style=" padding-bottom: 25%">

<h3 class="text-center"><%= group.topicname %></h3><br>

<%= link_to group_path(group) do %>
   <td><div class="text-center"> <%= image_tag group.avatar.url ,class:'img-circle img-responsive img-rounded',style:'width:100%' %></div><td>
<% end %>


     </div> 

  <% end %>
 </div> 
</div>

app/views/groups/new.html.erb
<html>
<head>
<style>
.div{
border:solid ;
}
.div1{
border:solid 1px;
width:100px;
float:left;
height:50px;
}
.div2{
border:solid 1px;
height:200px;
}

.div4{
border:solid 1px;
width:100px;
float:left;
height:50px;
}

.div5{
border:solid 1px;


height:200px;
}
</style>

</head>
<body>

<div class="container">
<h1 class="page-header">Adding New Group</h1>
<%= form_for :group ,url:groups_path do |f| %>



    <%= f.hidden_field :user_id, :value => current_user.id %>
 
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :topicname,class:"form-control" ,placeholder:"Enter group name....."%>
  </div>
   
 <% if @group.errors[:topicname].present? %>
          title can`t be blank
  <% end %>
     <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description ,class:"form-control" ,placeholder:"Enter group description....."%>
    </div>
  

 <% if @group.errors[:description].present? %>
          description can`t be blank
  <% end %>





    <%= fields_for :tag do |t| %>

    <%= t.label :interest %><br>
<div class="div2 well"></div>

            <%= t.hidden_field :name ,class:"text form-control"  %><br/><br />
    <%= t.hidden_field :id , class:"id" %>
<div class="div5 well"><% @tags.each do |tag| %>
<div class="div1 well" id="<%= tag.id %>" ><%= tag.name %></div>

        <% end %></div>
<% end %>


<br><br><br><br>
 <div class="form-group">
  <%= f.file_field :avatar %>
</div>
<div class="form-group">
  <%= f.label :location %>
   <%= f.select :location, 
    options_for_select(['Alexandria,Egypt','Cairo,Egypt']),
    class: 'form-control' %>
</div>

 
   <div class="form-group">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>




</div>
<script>
$(function() {
var interest="";
var intid="";
var lastvalue=[];
$(".div1").click(function(){

var text=$(this).children().remove().end().text();
var id=$(this).attr('id');
$(this).remove();
console.log(id);

interest=text+','+interest;
intid=id+','+intid;
$.ajax({
  type: "get",
  url: "/groups/new",
  dataType: "JSON",
  data: { 'data': interest,'id':intid },
  complete: function(data)
  {
var array = JSON.parse( data.responseText );


divtext=array[0].split(',');
divid=array[1].split(',');
    console.log(divtext);
$(".div2").append("<div class='div4 well' id="+divid[0]+">"+divtext[0]+"</div>");
$(".div4").click(function(){

var text1=$(this).children().remove().end().text();
var id1=$(this).attr('id');
$(this).remove();

var index = divtext.indexOf(text1);
if (index > -1) {
    divtext.splice(index, 1);
}

var index1 = divid.indexOf(id1);
if (index1 > -1) {
    divid.splice(index1, 1);
}

//var rest=$(".div4").children().remove().end().text();
console.log(array[0]);
console.log(divtext+"aya");
    console.log(typeof(array));
    $(".text").val(divtext);
    $(".id").val(divid);

  });}
});









})




});

</script>
</body>
</html>

app/views/groups/search.html.erb
 <div class="container">
 <div class="row">
  <% @groups.each do |group| %>
  <div class="col-sm-4" style=" padding-bottom: 25%">

<h3 class="text-center"><%= group.topicname %></h3><br>

<%= link_to group_path(group) do %>
   <div class="text-center"> <%= image_tag group.avatar.url ,class:'img-circle img-responsive img-rounded',style:'width:100%' %></div>
<% end %>

     </div> 
 
  <% end %>
 </div> 
</div>

app/views/groups/show.html.erb
<html>
<body>
  <div class="container">
  <% if current_user %>


<%  if current_user.isadmin == "admin" or current_user.id == @group.user_id %>
<%= link_to 'Edit', edit_group_path(@group), method: :get, class:"btn btn-warning pull-right" %>
<%= link_to 'Delete', group_path(@group), method: :delete,class:"btn btn-danger pull-right",
               data: { confirm: 'Are you sure?' } %>
<% end %>

<%if !@groupmemebe.present? and current_user.isadmin != "admin" and !@groupadmin.present? %>
<%= button_to 'join'  ,{:controller => "groups", :action => "action", :group_id => @group.id, :user_id=>current_user.id} ,:id=>"button", :method=>:post ,class:"btn btn-success pull-right" %>
<% end %>

<% end %>


  <h1 class="page-header text-capitalize"><%= @group.topicname %></h1>
  <div><%= image_tag(@group.avatar.url, class:'center-block') %></div>


 <% if current_user %>
<%if @groupcount.present?  or @group.user_id==current_user.id or current_user.isadmin=="admin"  %>



<%= link_to 'Add Event', new_group_event_path(@group), method: :get, class:"pull-right btn btn-info" %>
<% end %>
<%end%>
 
<p>
  <strong>Description:</strong>
  <%= @group.description %>
 </p> 
<p>
<strong>Number of Memebers:</strong>
<%= @count %>
 </p>
<h2>Events</h2>
<% @group.events.each do |event| %>
  
 <div class="row">
  <div class="well">
    
 

<div class="col-md-3">
  <%= image_tag event.avatar.url ,class:'img-responsive', style:'width: 100%' %>
</div>
 <h3><%= link_to event.title , group_event_path(@group,event), method: :get ,class:"text-capitalize lead",style:"color:black"%> <small> <%= event.date %> <%= event.time.to_s.split(' ')[1] %></small></h3>

<p><%= event.description %></p>
  
    
  
<div class="row">
<div class="pull-right">
<%  if current_user.isadmin == "admin" or current_user.id == event.user_id %>
<%= link_to 'Delete ', [@group, event],class:"btn btn-danger",
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

<%= link_to 'Edit', edit_group_event_path(@group,event), method: :get ,class:"btn btn-warning"%>
<% end %>
</div>
</div>
 </div> 
</div>
<% end %>
</div>