config/routes.rb
Rails.application.routes.draw do
  
  resources :tags

  get 'groups/search' => 'groups#search'
  get 'groups/places' => 'groups#places'
resources :groups do

  resources :events do 
resources:comments
end
end
get 'events/find' => 'events#find'
post 'groups/action'
post 'events/action'

resources :users
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :sessions
root :to => "groups#index"

end

app/models/user.rb
class User < ActiveRecord::Base




  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  

  validates :name, :password, :email, :gender, :age, :avatar, :country, :city , presence: true
  validates :password, length: { in: 6..20 }
  validates :email, length: { minimum: 6 } ,uniqueness: true
  validates :age, numericality: { only_integer: true }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  #attr_accessor :password,  :email, :name, :gender, :age, :city, :country, :avatar 

def self.authenticate(email, password)
    user = find_by_email(email)
    userPassword = find_by_password(password)
    if user && userPassword
      user
    else
      nil
    end
  end





has_many :events, :through => :event_admins , dependent: :destroy
	has_many :event_admins , dependent: :destroy
	has_many :comments , dependent: :destroy
	has_many :groups , dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


def index
   
end
def new
    @user = User.new
end

def create
    @user = User.new(user_params)
  if @user.save
       UserMailer.welcome_email(@user).deliver_now

     redirect_to groups_path

     #redirect_to "groups/index"

  else
   render 'new'
  end
end
def show
    @user = User.find(params[:id])
end
def edit

@user=User.find(params[:id])
end

def update

@user=User.find(params[:id])
if @user.update(user_params)
redirect_to @user
else 
render 'edit'
end
end

def destroy

@user=User.find(params[:id])

if @user.destroy
redirect_to users_path
end
end
def index
    @users = User.all
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :gender, :city, :country, :age, :avatar,:isadmin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>

  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>

  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
   
  </div>
  <div class="form-group">
    <%= f.label :gender, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
<%= f.radio_button :gender, "male", :checked => true %>
		<%= label :gender_male, :gender, "Male" %>
		<%= f.radio_button :gender, "female" %>
		<%= label :gender_female, :gender, "Female" %>
    </div>
    
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
		<%= f.number_field :age ,:class => 'form-control'%>
    </div>
   
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
         <%= f.select :city, 
    options_for_select([['Alexandria','Alexandria'],['Cairo','Cairo'],['paris','paris'],['london','london'],['Newyork','Newyork']], params[:city]),
    {}, { :class => 'span3 controls controls-row' } %>

    </div>
   
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      
  <%= f.select :country, 
    options_for_select([['UK','UK'],['US','US'],['Egypt','Egypt'],['France','France']], params[:country]),
    {}, { :class => 'span3 controls controls-row' } %>
    </div>
   
  </div>
  <div class="form-group">
    <%= f.label :avatar, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
   
  <%= f.file_field :avatar  %>
 <!--<%= f.text_field :avatar, :class => 'form-control' %>-->

    </div>
  
  </div>
 <%= f.hidden_field :isadmin, :value => "user" %>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      
    </div>
  </div>

<% end %>
</div>

app/views/users/edit.html.erb
<% if current_user.id == @user.id ||  current_user.isadmin == "admin"%>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<% else %>

    <p> it's not your profile so you can't edit it </p> 
   
     <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<% end %>

app/views/users/index.html.erb
<div class="container">
<% if current_user.isadmin == "admin" %>
 <%= link_to 'Groups', groups_path,class:"btn btn-info" %>
 <%= link_to 'Tags', tags_path,class:"btn btn-primary" %>
<%- model_class = User -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  
    <tr>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>





    </tr>
  <% @users.each do |user| %>
  <% if(user.isadmin != "admin") %>
<tr>
<td><%= user.name %></td>
<td><%= user.email %></td>
<td><%= user.gender %></td>
<td><%= user.age %></td>
<td><%= user.city %></td>
<td><%= user.country %></td>

<td><%= link_to 'Show', user_path(user) ,class:"btn btn-primary"%></td>
<td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-warning" %></td>
<td><%= link_to 'Destroy', user_path(user), method: :delete ,class:"btn btn-danger"%></td>
</tr>
<% end %>
<%end%>
<tbody>
<%else%>
<p> you are not the admin so you cant see this page</p>
 <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<%end%> 
</div> 

app/views/users/new.html.erb
<div class="container">
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<% if current_user.id == @user.id ||  current_user.isadmin == "admin"%>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @user.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @user.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @user.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @user.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>

<%=  @user.avatar %>



</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% else %>

    <p> it's not your profile so you can't see it </p> 
   
     <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<% end %>