config/routes.rb
Rails.application.routes.draw do
  
  resources :tags

  get 'groups/search' => 'groups#search'
  get 'groups/places' => 'groups#places'
resources :groups do

  resources :events do 
resources:comments
end
end
get 'events/find' => 'events#find'
post 'groups/action'
post 'events/action'

resources :users
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :sessions
root :to => "groups#index"

end

app/models/tag.rb
class Tag < ActiveRecord::Base

has_many :groups, :through => :tag_groups, dependent: :destroy
has_many :tag_groups, dependent: :destroy

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    # @tag.destroy
    # respond_to do |format|
    #   format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    @tag=Tag.find(params[:id])
if @tag.destroy
redirect_to tags_path
end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<% if current_user.isadmin == "admin" %>
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%else%>
<p> you are not the admin so you cant see this page</p>
 <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<%end%> 

app/views/tags/edit.html.erb
<% if current_user.isadmin == "admin"%>
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>
<%else%>
     <p>  you are not the admin so you can't edit it </p> 
 <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<% end %>

app/views/tags/index.html.erb
<% if current_user.isadmin == "admin" %>
<div class="container">
<p id="notice"><%= notice %></p>
<%= link_to 'Groups', groups_path,class:"btn btn-info" %>
 <%= link_to 'Users', users_path,class:"btn btn-primary" %>

<h1>Listing Tags</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag ,class:"btn btn-success"%></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) ,class:"btn btn-warning"%></td>
        <td><%= link_to 'Destroy', tag,class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path ,class:"btn btn-success"%>


<%else%>
<p> you are not the admin so you cant see this page</p>
 <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<%end%>  
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<% if current_user.isadmin == "admin" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

<% else %>
<p> you are not the admin so you cant see this page</p>
 <script type="text/javascript">
    window.location.href="http://localhost:3000/groups"  // put your correct path in a string here
  </script>
<% end %>