config/routes.rb
Rails.application.routes.draw do
  
  resources :tags

  get 'groups/search' => 'groups#search'
  get 'groups/places' => 'groups#places'
resources :groups do

  resources :events do 
resources:comments
end
end
get 'events/find' => 'events#find'
post 'groups/action'
post 'events/action'

resources :users
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :sessions
root :to => "groups#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.right{
	margin-right:30px;
}
</style>	
  <title>Meetup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
<nav class="navbar navbar-active">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
      <%= link_to 'Start Group', new_group_path, class:"btn navbar-btn btn-danger" %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
         <% if current_user %>
    Logged in as <%= current_user.name %>.
    <%= link_to "Log out", log_out_path ,class:"btn btn-danger"%>
  <% else %>
      	<li><%= link_to "Log in", log_in_path ,style:'color:black'%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      <%= link_to "Sign up", sign_up_path ,class:"btn navbar-btn btn-danger navbar-right"%>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>



<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

</body>
</html>